#!/bin/bash

printf """
====================================
~ VIMANA FRAMEW0RK | IMAGE BUILDER ~
====================================
"""

timedatectl set-ntp yes

printf "\n==> Building vimana image..."
docker build --no-cache=true --network=host -t vimana_framework:alpha .

printf "\n==> Testing image..."
docker run -it vimana_framework:alpha about
