project:
    author: s4dhu
    email: <s4dhul4bs[at]prontonmail.ch>
    git: https://github.com/s4dhulabs/vimana-framework
    name: Vimana Framework
    site: https://sadhulabs.substack.com/
    tag: alpha
    version: v0.9
settings:
    arg_parser:
        require_args:
        - --save-case
        - --target
        - --file
        - --ip-range
        - --cidr-range
        - --target-list
        - --port
        - --port-list
        - --port-range
        - --fuzzer
        - --proxy
        - --proxy-type
        - --nmap-xml
        - --abduct
        - --module
        - --session
        - --target-url
        - --project-dir
        - --target-dir
        - --project
        - --use-request
        - --plugin
        - --case
        - --data
        - --form-input-target
        - --target-input
        - --django-version
        - --inspect
        - --methods
        - --method
        - --fuzzspecs
        - --fuzzspec
        - -m
        - --flush-spec
        - --set-path
        - --custom-variations
        - --set-parameter
        - --set-param
    case_set:
        cases_path: core/cases/
        cases_yf: core/cases/*.yaml
        empty_msg: '[{}] It seems like you didn''t create any case yet, or they were
            flushed.'
    sessions: core/sessions/
    siddhis_set:
        dir: siddhis/
        list:
        - djunch
        - 2pacx
        - prana
        - dmt
        - flame
        - d4m8
        - sttinger
        - jungle
        - viwec
        - atlatl
        - viewscan
        - tictrac
    utils:
        random_headers: res/random_headers.yaml
