settings = {
    'LOG_ENABLED':False,
    'LOG_LEVEL': "DEBUG",
    'COOKIES_ENABLED':True,
    'TELNETCONSOLE_ENABLED': False,
    'RANDOMIZE_DOWNLOAD_DELAY': True,
    'RETRY_TIMES': 1,
    'HTTPERROR_ALLOW_ALL':True,
    #'HTTPERROR_ALLOWED_CODES': [200,301,302,400,403,404,500],
    'REDIRECT_ENABLED':True,
    'USER_AGENT': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko)',
    'AUTOTHROTTLE_ENABLED': False,
    'DOWNLOAD_TIMEOUT':5,
    #'DOWNLOAD_DELAY':5,
    'HTTPCACHE_ENABLED':True,
    #'CONCURRENT_REQUESTS': 200,
    #'CONCURRENT_REQUESTS_PER_IP':200,
    'DEPTH_LIMIT':0
}

