#! /bin/bash
#  __ _
#   \/imana 2016
#   [|-ramewørk
#
#
# Author: s4dhu
# Email: <s4dhul4bs[at]prontonmail[dot]ch
# Git: @s4dhulabs
# Mastodon: @s4dhu
# 
# This file is part of Vimana Framework Project.

cd ~/
git clone https://github.com/s4dhulabs/vimana-framework.git 
cd vimana-framework
source scripts/setup

